import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { AppProps } from 'next/app'
import NextNProgress from 'nextjs-progressbar';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  // title: 'Create Next App',
  // description: 'Generated by create next app',
}

export default function RootLayout({ Component, pageProps }: AppProps) {
  return (
    <>
    <NextNProgress color="violet" height={2}/>
      <div className="absolute w-full h-screen mx-auto font-sans">
        <div className="container mx-auto">
        <Navbar />
        <main className=''>
          <Component {...pageProps} />
        </main>
        </div>
        <Footer/>
      </div>
    </>
  )
}
